### PR TITLE
Dink smallwood port for ps vita?

### PR DESCRIPTION
**Pull request by joasnake**
Hi,

We were discussing with @SethRobinson that if this can be used to create a port of dink smallwood hd for ps vita. Any such plans it would be a great help for the community
http://www.dinknetwork.com/forum.cgi?MID=207116&Posts=5

### CODE REVIEW

**Comment by NabsiYa** [comment]
> 
> 
> Hi, my proton port for PS Vita is not complete yet and that's why i don't wish to push the source into the main repository as pull request but since you mentioned that you'd want to port "Dink smallwood" for PS Vita i would gladly do that if you wish so but i hope you would refrain from trying to pull request my code until its stable because i don't want any bugs due to my unfinished code.
> 
> We were discussing with @SethRobinson that if this can be used to create a port of dink smallwood hd for ps vita. Any such plans it would be a great help for the community http://www.dinknetwork.com/forum.cgi?MID=207116&Posts=5

**Comment by iProgramMC** [comment]
Yeah honestly a PSVita port of old Proton games would be cool. ~~Especially Tanked~~

**Comment by joasnake** [comment]
> Update: i managed to get it running but it has still countless of bugs so no gameplay yet but MainMenu works!
> 
> https://streamable.com/mlmuzf

Wow this is amazing thanks for the effort , i am already having dreams of playing dink smallwood on vita lol, if we can get a version out for vita i am the community would love to help out with the bugs list and maybe @SethRobinson can help as well

**Comment by joasnake** [comment]
wow that is a amazing speed any idea on putting a vpk out, would love to test it on my pstv

**Pull request closed without merging**
